"""add midi_filename to projects table

Revision ID: 0353ba97cfb1
Revises: afd89a2a9377
Create Date: 2026-09-26 15:15:57.962150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0353ba97cfb1'
down_revision: Union[str, Sequence[str], None] = 'afd89a2a9377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('midi_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'midi_filename')
    # ### end Alembic commands ###
